print('hello world')
x = print('hello world')
y = print('hello world')
print('hello world')
print('hello world')
print('hello world')
print('hello world)
print('hello world')
print('hello world')
print('hello world')
print('hello world')